<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Amenity;
use App\Models\User;
use App\Models\AmenityReservation;
use Carbon\Carbon;

class RealAmenityReservationSeeder extends Seeder
{
    public function run()
    {
        $amenities = Amenity::all();
        $users = User::has('resident')->get();

        if ($amenities->isEmpty() || $users->isEmpty()) {
            $this->command->error('Amenities or residents missing.');
            return;
        }

        $this->command->info('Generating controlled amenity reservations...');

        $startDate = Carbon::today();
        $daysToGenerate = 14;

        // RULES
        $amenityLimits = [5, 7, 8];
        $dayLimits = [2, 3, 6];

        foreach ($amenities as $amenity) {

            // Random limit per amenity
            $amenityMax = collect($amenityLimits)->random();
            $amenityCount = 0;
x
            $this->command->info("Amenity: {$amenity->name} | Max: {$amenityMax}");

            $bufferMinutes = $amenity->buffer_minutes ?? 16;

            for ($i = 0; $i < $daysToGenerate; $i++) {

                if ($amenityCount >= $amenityMax) {
                    break;
                }

                $currentDate = $startDate->copy()->addDays($i);
                $dateStr = $currentDate->format('Y-m-d');

                // Random limit per day
                $dayMax = collect($dayLimits)->random();
                $dayCount = 0;

                $startTime = $currentDate->copy()->setTime(8, 0);
                $endTime = $currentDate->copy()->setTime(21, 0);
                $cursor = $startTime->copy();

                while ($cursor->lt($endTime)) {

                    if ($amenityCount >= $amenityMax || $dayCount >= $dayMax) {
                        break;
                    }

                    // 20% chance to skip (gap)
                    if (rand(1, 100) <= 20) {
                        $cursor->addMinutes(rand(30, 120));
                        continue;
                    }

                    $durationHours = rand(1, 3);
                    $durationMinutes = $durationHours * 60;

                    if ($cursor->copy()->addMinutes($durationMinutes)->gt($endTime)) {
                        break;
                    }

                    $slotStart = $cursor->format('H:i');
                    $slotEnd = $cursor->copy()->addMinutes($durationMinutes)->format('H:i');

                    $status = $this->getRandomStatus();
                    $paymentStatus = ($status === 'approved')
                        ? (rand(0, 1) ? 'paid' : 'unpaid')
                        : 'unpaid';

                    AmenityReservation::create([
                        'amenity_id' => $amenity->id,
                        'resident_id' => $users->random()->id,
                        'date' => $dateStr,
                        'time_slot' => "{$slotStart} - {$slotEnd}",
                        'guest_count' => rand(1, 15),
                        'total_price' => ($amenity->price ?? 100) * $durationHours,
                        'status' => $status,
                        'payment_status' => $paymentStatus,
                        'notes' => 'Generated by RealAmenityReservationSeeder',
                    ]);

                    $amenityCount++;
                    $dayCount++;

                    // Move cursor forward
                    $cursor->addMinutes($durationMinutes + $bufferMinutes);
                }
            }
        }

        $this->command->info('Done! Controlled reservations generated.');
    }

    private function getRandomStatus()
    {
        $rand = rand(1, 100);

        if ($rand <= 70) return 'approved';
        if ($rand <= 90) return 'pending';

        return 'rejected';
    }
}
